### ISSUE TITLE
Running setup on a vanilla x86 arch Mac results in errors

### ISSUE THREAD

**Issue by tdstark** [customink/crypteia#20]
Running the setup command for the first time results in the following error:
```
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-linux-gnu`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `core`
    --> /Users/thomasstark/.cargo/registry/src/github.com-1ecc6299db9ec823/pin-project-lite-0.2.9/src/lib.rs:1503:9
```
I'm assuming this can easily be resolved with a few additional package installs, but I'm leaving this here in case someone wants to smooth out the setup.

**Comment by metaskills** [comment]
Thanks, was this the only issue? Curious if you had thoughts on Codespaces (https://github.com/customink/crypteia#development) or if we should add directions on how to use the "devcontainers" spec which backs Codespaces so Mac, Anyone, can use the same development containers with Docker. Thoughts?

**Comment by metaskills** [comment]
So there are 3 options here that cover any editor, any platform. Use the Dev Containers. You can do that with Codespacers, VS Code's Dev Container extension, or the Dev Container CLI via NPM. Details now in [README](https://github.com/customink/crypteia#development) via this commit. https://github.com/customink/crypteia/commit/576b3e5995331ef4586bc2a7f2026c5b778db757
